### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by dogmatic69** [andheiberg/vzaar#3]
Any change of an update here?

Actually just checked and seems like this is not just a clone as I first thought. Does the code work for the current API?

**Comment by andheiberg** [comment]
When did something change in the Vzaar API? I'm not on the project that uses this anymore, so I'm not sure that it works, but I would think so.

**Comment by papa-smurf** [comment]
We don't use the full package but authenticating and uploading/removing videos works perfectly fine.

**Comment by andheiberg** [comment]
Awesome :)
